<?php

namespace Cmt\TagBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhraseRepository extends EntityRepository
{
}