security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_PROSPECT:      ROLE_USER
        ROLE_ADMIN:         [ROLE_PROSPECT, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    providers:
        fos_userbundle:
                    id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: /profile
            logout:       true
            anonymous:    true
            remember_me:
                key:      085facaefe37df66710a1c892dbdc3b4
                lifetime: 604800
                path:     /
                domain:   commeaupotager.fr
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: ^/register, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: ^/resetting, roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
        - { path: ^/admin, roles: 'ROLE_ADMIN' }
        - { path: ^/admin/, roles: 'ROLE_ADMIN' }
