parameters:
#    cmt_core.example.class: Cmt\CoreBundle\Example

services:
#    cmt_core.example:
#        class: %cmt_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
