# src/Cmt/CoreBundle/Resources/config/validation.yml
Cmt\CoreBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
        email:
            - NotBlank: ~
        plainPassword:
            - NotBlank: ~
